import { getTranslations, type Locale } from '../i18n'

/**
 * The feature story on the home page: one section per capability, each
 * explaining exactly one thing and showing it.
 *
 * The imagery is generated by the app repo's screenshot pipeline
 * (`store_assets`, `npm run web && npm run export-web`) and lands in
 * `public/app/<locale>/<id>.webp`. Screenshots are localised, hence the
 * locale in the path — a German visitor must not see a French score
 * sheet.
 *
 * The images carry no background of their own. The devices and the
 * cropped cards sit on transparency and the band behind them belongs
 * to the page, alternating black and grey down the section. That is
 * why the image element has no border, radius or shadow: there is no
 * rectangle to frame.
 *
 * Order and ids have to match `storySections` in the i18n files.
 */

const SECTION_IDS = [
  'modes',
  'gestures',
  'rules',
  'mirror',
  'stats',
  'summary',
] as const

export function AppStorySections({ lang = 'de' }: { lang?: Locale }) {
  const t = getTranslations(lang).appStory

  return (
    <section id="app-story" className="w-full border-t border-zinc-800">
      <div className="bg-zinc-950">
        <div className="container px-4 md:px-6 mx-auto pt-12 pb-6 md:pt-20 md:pb-10">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-emerald-500/10 px-3 py-1 text-sm text-emerald-400 border border-emerald-500/20">
              {t.badge}
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              {t.title}{' '}
              <span className="text-emerald-400">{t.titleAccent}</span>
            </h2>
            <p className="max-w-[42rem] text-zinc-400 md:text-lg">
              {t.description}
            </p>
          </div>
        </div>
      </div>

      {SECTION_IDS.map((id, i) => {
        const item = t.sections[id]
        // Alternating sides give the eye a rhythm on a long page.
        // Below md the grid collapses and the kicker and headline
        // always come first, so the reader knows what they are
        // looking at before the picture arrives.
        const imageFirst = i % 2 === 1
        return (
          <div
            key={id}
            className={`w-full ${i % 2 === 0 ? 'bg-zinc-950' : 'bg-zinc-900'}`}
          >
            <div className="container px-4 md:px-6 mx-auto">
              <article className="grid gap-8 md:gap-12 md:grid-cols-2 items-center py-12 md:py-20">
                <div
                  className={
                    imageFirst
                      ? 'order-1 md:order-2 space-y-4'
                      : 'order-1 space-y-4'
                  }
                >
                  <p className="text-xs uppercase tracking-[0.18em] text-emerald-400/80 font-medium">
                    {item.kicker}
                  </p>
                  <h3 className="text-2xl sm:text-3xl font-bold tracking-tight text-zinc-100">
                    {item.title}
                  </h3>
                  <p className="text-zinc-400 leading-relaxed">{item.body}</p>
                  <ul className="flex flex-wrap gap-2 pt-1">
                    {item.proof.map((chip) => (
                      <li
                        key={chip}
                        className="rounded-full border border-zinc-800 bg-zinc-900 px-3 py-1 text-sm text-zinc-300"
                      >
                        {chip}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className={imageFirst ? 'order-2 md:order-1' : 'order-2'}>
                  <img
                    src={`/app/${lang}/${id}.webp`}
                    alt={item.imageAlt}
                    width={2400}
                    height={1240}
                    loading="lazy"
                    decoding="async"
                    className="w-full h-auto"
                  />
                </div>
              </article>
            </div>
          </div>
        )
      })}
    </section>
  )
}
